name: dlpo
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - torchaudio
  - pytorch-cuda=11.8
  - pip
  - pip:
    - pytorch-lightning>=1.7.0
    - omegaconf>=2.2.0
    - scipy>=1.9.0
    - numpy>=1.21.0
    - tqdm>=4.64.0
    - pandas>=1.4.0
    - g2p-en>=2.1.0
    - pypinyin>=0.47.0
    - tensorboard>=2.9.0
    - librosa>=0.9.0
    - matplotlib>=3.5.0
    - soundfile>=0.10.0 